### ISSUE TITLE
Nodejs インストール

### ISSUE THREAD

**Issue by akiakishitai** [akiakishitai/my-code-server#13]
ベースイメージで _Nodejs_ がインストールされなくなったので対処する。

linuxserver.io の Docker イメージにおいては [_Docker Mods_](https://docs.linuxserver.io/general/container-customization#docker-mods) という仕組みが用意されている。 
よって [linuxserver/docker-mods](https://github.com/linuxserver/docker-mods) で提供されている [`code-server-nodejs`](https://github.com/linuxserver/docker-mods/tree/code-server-nodejs) を利用すれば良さそう。

```
spec:
  containers:
  - env:
    - name: DOCKER_MODS
      value: "linuxserver/mods:code-server-nodejs"
```
